// Generated by scripts/clean-sprites.mjs from art/settlement-early.png. Do not edit by hand.
//
// Where each early era building sits in the sheet, and where on it the building meets the ground.
// Pixels, with the origin at the top left of the sheet. The same shape as the manifests that ship
// beside the other sheets, so that billboards.ts reads them all the same way.

import type { AtlasManifest } from './billboards'

export const SETTLEMENT_ATLAS: AtlasManifest = {
  texture: 'settlement-early.png',
  size: [1024, 398],
  pieces: {
    barn: { x: 4, y: 228, w: 219, h: 166, anchorX: 85.1, anchorY: 156.3 },
    frame: { x: 227, y: 228, w: 220, h: 155, anchorX: 122.3, anchorY: 152.4 },
    hall: { x: 4, y: 4, w: 170, h: 220, anchorX: 63.3, anchorY: 213.8 },
    lodge: { x: 178, y: 4, w: 220, h: 195, anchorX: 134.4, anchorY: 175.1 },
    longhouse: { x: 402, y: 4, w: 219, h: 175, anchorX: 109.3, anchorY: 172.3 },
    steading: { x: 451, y: 228, w: 220, h: 155, anchorX: 83.0, anchorY: 139.4 },
    yard: { x: 625, y: 4, w: 219, h: 169, anchorX: 83.0, anchorY: 159.3 },
  },
}
