// The three tiling detail textures. Art direction brief section 1 says no textures anywhere, and
// that was right about terrain art: none of these is terrain art. They are one small greyscale tooth
// each, tiled at high frequency and multiplied over the vertex colour, which is the thing that stops
// a vertex-coloured surface reading as a gradient. Forty-six kilobytes for all three.
//
// They are generated by scripts/make-textures.mjs and committed. Nothing waits on them: each one is
// a shared uniform holding a flat grey stand-in, so the map draws from the first frame and every
// material picks the real thing up the moment it arrives. A slow or failed fetch costs the tooth and
// nothing else.

import * as THREE from 'three'

export interface DetailTextures {
  grain: THREE.IUniform
  rock: THREE.IUniform
  ripple: THREE.IUniform
  /** Resolves when every one that is going to arrive has arrived. Never rejects. */
  ready: Promise<void>
}

function placeholder(): THREE.DataTexture {
  const t = new THREE.DataTexture(new Uint8Array([128]), 1, 1, THREE.RedFormat)
  t.unpackAlignment = 1
  t.needsUpdate = true
  return t
}

let cached: DetailTextures | null = null

/** Load once for the life of the page. The same three serve every world. */
export function detailTextures(onArrive?: () => void): DetailTextures {
  if (cached) return cached
  const out: DetailTextures = {
    grain: { value: placeholder() },
    rock: { value: placeholder() },
    ripple: { value: placeholder() },
    ready: Promise.resolve(),
  }
  const loader = new THREE.TextureLoader()
  const load = (name: string, into: THREE.IUniform) => new Promise<void>((done) => {
    loader.load(
      `textures/${name}.png`,
      (tex) => {
        tex.wrapS = THREE.RepeatWrapping
        tex.wrapT = THREE.RepeatWrapping
        tex.magFilter = THREE.LinearFilter
        tex.minFilter = THREE.LinearMipmapLinearFilter
        tex.generateMipmaps = true
        tex.anisotropy = 4
        tex.needsUpdate = true
        into.value = tex
        done()
      },
      undefined,
      () => done(),   // one that will not load simply stays flat
    )
  })
  out.ready = Promise.all([load('grain', out.grain), load('rock', out.rock), load('ripple', out.ripple)])
    .then(() => { if (onArrive) onArrive() })
    .catch(() => { /* silent: the map is fine without them */ })
  cached = out
  return out
}
