// Save format, build specification section 9. The world is regenerated, not deserialised: loading
// runs worldgen from the seed, then applies tileDeltas. Saves stay in the low kilobytes.
// Write on every turn boundary and on visibilitychange. Never beforeunload.

import { SCHEMA_VERSION, WORLDGEN_VERSION } from '../sim/constants'
import type { GameState, Settings, Tile, TileDelta, RngState } from '../sim/state'
import { generateWorld, worldToState } from '../sim/worldgen'
import { playRng } from '../sim/rng'

export interface SaveState {
  schemaVersion: number
  worldgenVersion: number
  seed: string
  settings: Settings
  turn: number
  tileDeltas: Record<number, TileDelta>
  charters: GameState['charters']
  settlements: GameState['settlements']
  units: GameState['units']
  predecessors: GameState['predecessors']
  market: GameState['market']
  company: GameState['company']
  declaration: GameState['declaration']
  dispatch: GameState['dispatch']
  intent: string
  flags: GameState['flags']
  rngWorld: RngState
  nextId: number
  telemetry: GameState['telemetry']
  opportunitiesShown: GameState['opportunitiesShown']
  transits: GameState['transits']
  savedAt: number
}

const DELTA_FIELDS: (keyof TileDelta)[] = ['forest', 'road', 'improved', 'goldReserve', 'owner', 'worked', 'workings', 'explored']

// The pristine world for a seed and settings is deterministic, so it is cached for diffing.
let pristineKey = ''
let pristineTiles: Tile[] | null = null

function pristine(seed: string, settings: Settings): Tile[] {
  const key = seed + '|' + JSON.stringify({ ...settings, audio: undefined, pace: undefined, firstGame: undefined, difficulty: undefined, turns: undefined, crossing: undefined })
  if (key !== pristineKey || !pristineTiles) {
    pristineTiles = generateWorld(seed, settings).tiles
    pristineKey = key
  }
  return pristineTiles
}

export function toSave(s: GameState, now = Date.now()): SaveState {
  const base = pristine(s.seed, s.settings)
  const tileDeltas: Record<number, TileDelta> = {}
  for (let i = 0; i < s.world.tiles.length; i++) {
    const a = s.world.tiles[i], b = base[i]
    let d: TileDelta | null = null
    for (const f of DELTA_FIELDS) {
      if (a[f] !== b[f]) { if (!d) d = {}; (d as Record<string, unknown>)[f] = a[f] }
    }
    if (d) tileDeltas[i] = d
  }
  return {
    schemaVersion: SCHEMA_VERSION,
    worldgenVersion: WORLDGEN_VERSION,
    seed: s.seed,
    settings: s.settings,
    turn: s.turn,
    tileDeltas,
    charters: s.charters,
    settlements: s.settlements,
    units: s.units,
    predecessors: s.predecessors,
    market: s.market,
    company: s.company,
    declaration: s.declaration,
    dispatch: s.dispatch,
    intent: s.intent,
    flags: s.flags,
    rngWorld: s.rng.world,
    nextId: s.nextId,
    telemetry: s.telemetry,
    opportunitiesShown: s.opportunitiesShown,
    transits: s.transits ?? [],
    savedAt: now,
  }
}

export function fromSave(save: SaveState, now = Date.now()): GameState {
  if (save.schemaVersion !== SCHEMA_VERSION) throw new Error(`Save is schema ${save.schemaVersion}, this build reads ${SCHEMA_VERSION}`)
  if (save.worldgenVersion !== WORLDGEN_VERSION) throw new Error(`Save was generated by worldgen ${save.worldgenVersion}, this build is ${WORLDGEN_VERSION}`)
  const world = generateWorld(save.seed, save.settings)
  const w = worldToState(world)
  for (const [k, d] of Object.entries(save.tileDeltas)) {
    const t = w.tiles[Number(k)]
    if (t) Object.assign(t, d)
  }
  return {
    schemaVersion: save.schemaVersion,
    worldgenVersion: save.worldgenVersion,
    seed: save.seed,
    settings: save.settings,
    turn: save.turn,
    world: w,
    charters: save.charters,
    settlements: save.settlements,
    units: save.units,
    predecessors: save.predecessors,
    market: save.market,
    company: save.company,
    declaration: save.declaration,
    dispatch: save.dispatch,
    intent: save.intent,
    flags: save.flags,
    rng: { world: save.rngWorld, play: playRng(now) },
    nextId: save.nextId,
    telemetry: save.telemetry,
    opportunitiesShown: save.opportunitiesShown,
    actionsThisTurn: 0,
    transits: save.transits ?? [],
  }
}

export const STORAGE_KEY = 'fairholm.save.v' + SCHEMA_VERSION
export const SETTINGS_KEY = 'fairholm.settings'

export function writeLocal(s: GameState): boolean {
  try {
    const save = toSave(s)
    localStorage.setItem(STORAGE_KEY, JSON.stringify(save))
    return true
  } catch {
    return false
  }
}

export function readLocal(): SaveState | null {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (!raw) return null
    return JSON.parse(raw) as SaveState
  } catch {
    return null
  }
}

export function clearLocal() {
  try { localStorage.removeItem(STORAGE_KEY) } catch { /* ignore */ }
}

export function readLastSettings(): Partial<Settings> | null {
  try {
    const raw = localStorage.getItem(SETTINGS_KEY)
    return raw ? JSON.parse(raw) as Partial<Settings> : null
  } catch { return null }
}
export function writeLastSettings(settings: Settings) {
  try { localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings)) } catch { /* ignore */ }
}

export async function requestPersistence() {
  try {
    if (navigator.storage && navigator.storage.persist) await navigator.storage.persist()
  } catch { /* not available */ }
}

// ---- export and import ------------------------------------------------------------------------

async function gzip(text: string): Promise<Uint8Array> {
  if (typeof CompressionStream === 'undefined') return new TextEncoder().encode(text)
  const cs = new CompressionStream('gzip')
  const writer = cs.writable.getWriter()
  writer.write(new TextEncoder().encode(text))
  writer.close()
  const buf = await new Response(cs.readable).arrayBuffer()
  return new Uint8Array(buf)
}

async function gunzip(bytes: Uint8Array): Promise<string> {
  if (typeof DecompressionStream === 'undefined') return new TextDecoder().decode(bytes)
  const ds = new DecompressionStream('gzip')
  const writer = ds.writable.getWriter()
  writer.write(bytes as unknown as BufferSource)
  writer.close()
  const buf = await new Response(ds.readable).arrayBuffer()
  return new TextDecoder().decode(buf)
}

function toBase64(bytes: Uint8Array): string {
  let bin = ''
  for (let i = 0; i < bytes.length; i += 0x8000) bin += String.fromCharCode(...bytes.subarray(i, i + 0x8000))
  return btoa(bin)
}
function fromBase64(b64: string): Uint8Array {
  const bin = atob(b64.trim())
  const out = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i)
  return out
}

export const EXPORT_HEADER = 'FAIRHOLM1:'

/** Export the save as a text file: a header, then gzip of the JSON, base64. */
export async function exportText(s: GameState): Promise<string> {
  const json = JSON.stringify(toSave(s))
  const gz = await gzip(json)
  const isGz = gz[0] === 0x1f && gz[1] === 0x8b
  return (isGz ? EXPORT_HEADER : 'FAIRHOLM0:') + toBase64(gz)
}

export async function importText(text: string): Promise<SaveState> {
  const trimmed = text.trim()
  if (trimmed.startsWith('{')) return JSON.parse(trimmed) as SaveState
  const idx = trimmed.indexOf(':')
  const header = trimmed.slice(0, idx + 1)
  const body = trimmed.slice(idx + 1)
  const bytes = fromBase64(body)
  const json = header === EXPORT_HEADER ? await gunzip(bytes) : new TextDecoder().decode(bytes)
  return JSON.parse(json) as SaveState
}

export function exportFilename(s: GameState): string {
  return `fairholm-${s.seed}-turn${s.turn}.txt`
}

/** Share through navigator.share with a download fallback, persistence brief section 5. */
export async function shareExport(s: GameState): Promise<'shared' | 'downloaded'> {
  const text = await exportText(s)
  const name = exportFilename(s)
  const file = new File([text], name, { type: 'text/plain' })
  try {
    if (navigator.share && navigator.canShare && navigator.canShare({ files: [file] })) {
      await navigator.share({ files: [file], title: 'Fairholm save' })
      return 'shared'
    }
  } catch { /* fall through to download */ }
  const url = URL.createObjectURL(file)
  const a = document.createElement('a')
  a.href = url
  a.download = name
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 5000)
  return 'downloaded'
}

export function importFromFile(file: File): Promise<SaveState> {
  return file.text().then(importText)
}
